%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\jpc5s\OneDrive - University of Virginia\PatientData\EAOB\52104\cgm.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/06/04 16:20:34

%% Initialize variables.
filename = 'C:\Users\jpc5s\OneDrive - University of Virginia\PatientData\EAOB\52104\cgm.csv';
endRow = 1;

%% Format for each line of text:
%   column1: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%15s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Remove white space around all cell columns.
dataArray{1} = strtrim(dataArray{1});

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
cgm1 = table(dataArray{1:end-1}, 'VariableNames', {'IdReadingtak'});

%% Clear temporary variables
clearvars filename endRow formatSpec fileID dataArray ans;