%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\jpc5s\OneDrive - University of Virginia\PatientData\EAOB\52104\cgm.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/06/04 16:36:13

%% Initialize variables.
filename = 'C:\Users\jpc5s\OneDrive - University of Virginia\PatientData\EAOB\52104\cgm.csv';

%% Format for each line of text:
%   column1: text (%s)
%	column2: text (%s)
%   column3: categorical (%C)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f %s %s %s %s %s';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN,  'ReturnOnError', false);

%% Remove white space around all cell columns.
dataArray{1} = strtrim(dataArray{1});
dataArray{2} = strtrim(dataArray{2});

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
cgm2 = table(dataArray{1:end-1}, 'VariableNames', {'Id','Readingtakenat','Reading','PatientCreatedat','Updatedat','Cgmdatafile'});

%% Clear temporary variables
clearvars filename formatSpec fileID dataArray ans;